// Added for Alternator:
var Module = {
    locateFile(path) {
      return 'compositions/pd/' + path
    }
}

async function setup(sampleRate) {
    await new Promise(resolve => (Module.onRuntimeInitialized = resolve))
    Module._setup(sampleRate)
}

function process(output) {
    buffer = Module._malloc(output.length * output.BYTES_PER_ELEMENT)
    Module.HEAPF32.set(output, buffer / output.BYTES_PER_ELEMENT)
    const out = Module._process(buffer, output.length)
    output.set(new Float32Array(Module.HEAP32.buffer, buffer, output.length))
    Module._free(buffer)
    return out
}


var g;g||(g=typeof Module !== 'undefined' ? Module : {});g.Ya||(g.Ya=0);g.Ya++;
(function(a){function b(m,t,p,r){if("object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node)require("fs").readFile(m,function(u,x){u?r(u):p(x.buffer)});else{var q=new XMLHttpRequest;q.open("GET",m,!0);q.responseType="arraybuffer";q.onprogress=function(u){var x=t;u.total&&(x=u.total);if(u.loaded){q.Ca?g.Ia[m].loaded=u.loaded:(q.Ca=!0,g.Ia||(g.Ia={}),g.Ia[m]={loaded:u.loaded,total:x});var v=x=u=0,D;for(D in g.Ia){var F=g.Ia[D];u+=F.total;x+=F.loaded;v++}u=
Math.ceil(u*g.Ya/v);g.setStatus&&g.setStatus("Downloading data... ("+x+"/"+u+")")}else!g.Ia&&g.setStatus&&g.setStatus("Downloading data...")};q.onerror=function(){throw Error("NetworkError for: "+m);};q.onload=function(){if(200==q.status||304==q.status||206==q.status||0==q.status&&q.response)p(q.response);else throw Error(q.statusText+" : "+q.responseURL);};q.send(null)}}function c(m){console.error("package error:",m)}function d(){function m(q,u,x){this.start=q;this.end=u;this.audio=x}function t(q){if(!q)throw"Loading data file failed."+
Error().stack;if(!(q instanceof ArrayBuffer))throw"bad input to processPackageData"+Error().stack;q=new Uint8Array(q);m.prototype.Eb=q;q=a.files;for(var u=0;u<q.length;++u)m.prototype.Ca[q[u].filename].onload();g.removeRunDependency("datafile_thing.data")}m.prototype={Ca:{},open:function(q,u){this.name=u;this.Ca[u]=this;g.addRunDependency("fp "+this.name)},send:function(){},onload:function(){this.$a(this.Eb.subarray(this.start,this.end))},$a:function(q){g.FS_createDataFile(this.name,null,q,!0,!0,
!0);g.removeRunDependency("fp "+this.name);this.Ca[this.name]=null}};for(var p=a.files,r=0;r<p.length;++r)(new m(p[r].start,p[r].end,p[r].audio||0)).open("GET",p[r].filename);g.addRunDependency("datafile_thing.data");g.qb||(g.qb={});g.qb["thing.data"]={Mb:!1};n?(t(n),n=null):h=t}"object"===typeof window?window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+"/"):"undefined"===typeof process&&"undefined"!==typeof location&&encodeURIComponent(location.pathname.toString().substring(0,
location.pathname.toString().lastIndexOf("/"))+"/");"function"!==typeof g.locateFilePackage||g.locateFile||(g.locateFile=g.locateFilePackage,k("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));var e=g.locateFile?g.locateFile("thing.data",""):"thing.data",f=a.remote_package_size,h=null,n=g.getPreloadedPackage?g.getPreloadedPackage(e,f):null;n||b(e,f,function(m){h?(h(m),h=null):n=m},c);g.calledRun?d():(g.preRun||(g.preRun=
[]),g.preRun.push(d))})({files:[{filename:"/thing.pd",start:0,end:505}],remote_package_size:505,package_uuid:"d8708115-9a14-4297-b67c-86ab28ff004b"});var aa={},l;for(l in g)g.hasOwnProperty(l)&&(aa[l]=g[l]);var ca="./this.program";function da(a,b){throw b;}var ea="object"===typeof window,fa="function"===typeof importScripts,ha="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node,w="",ia,ja,ka,la,ma;
if(ha)w=fa?require("path").dirname(w)+"/":__dirname+"/",ia=function(a,b){la||(la=require("fs"));ma||(ma=require("path"));a=ma.normalize(a);return la.readFileSync(a,b?null:"utf8")},ka=function(a){a=ia(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},ja=function(a,b,c){la||(la=require("fs"));ma||(ma=require("path"));a=ma.normalize(a);la.readFile(a,function(d,e){d?c(d):b(e.buffer)})},1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/")),process.argv.slice(2),"undefined"!==typeof module&&
(module.exports=g),process.on("uncaughtException",function(a){if(!(a instanceof na))throw a;}),process.on("unhandledRejection",y),da=function(a,b){if(noExitRuntime||0<oa)throw process.exitCode=a,b;process.exit(a)},g.inspect=function(){return"[Emscripten Module object]"};else if(ea||fa)fa?w=self.location.href:"undefined"!==typeof document&&document.currentScript&&(w=document.currentScript.src),w=0!==w.indexOf("blob:")?w.substr(0,w.lastIndexOf("/")+1):"",ia=function(a){var b=new XMLHttpRequest;b.open("GET",
a,!1);b.send(null);return b.responseText},fa&&(ka=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ja=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var pa=g.print||console.log.bind(console),k=g.printErr||console.warn.bind(console);
for(l in aa)aa.hasOwnProperty(l)&&(g[l]=aa[l]);aa=null;g.thisProgram&&(ca=g.thisProgram);g.quit&&(da=g.quit);var qa;g.wasmBinary&&(qa=g.wasmBinary);var noExitRuntime=g.noExitRuntime||!0;"object"!==typeof WebAssembly&&y("no native wasm support detected");var ra,sa=!1;function assert(a,b){a||y("Assertion failed: "+b)}var ta="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ua(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&ta)return ta.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|h:(e&7)<<18|f<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function z(a){return a?ua(A,a,void 0):""}
function va(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var h=a.charCodeAt(f);if(55296<=h&&57343>=h){var n=a.charCodeAt(++f);h=65536+((h&1023)<<10)|n&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e}
function wa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function xa(a){var b=wa(a)+1,c=ya(b);c&&va(a,C,c,b);return c}function za(a,b){for(var c=0;c<a.length;++c)C[b++>>0]=a.charCodeAt(c);C[b>>0]=0}var Aa,C,A,Ba,Ca,E,Da,Ea=[],Fa=[],Ga=[],oa=0;function Ha(){var a=g.preRun.shift();Ea.unshift(a)}var Ia=0,Ja=null,Ka=null;
function La(){Ia++;g.monitorRunDependencies&&g.monitorRunDependencies(Ia)}function Ma(){Ia--;g.monitorRunDependencies&&g.monitorRunDependencies(Ia);if(0==Ia&&(null!==Ja&&(clearInterval(Ja),Ja=null),Ka)){var a=Ka;Ka=null;a()}}g.preloadedImages={};g.preloadedAudios={};function y(a){if(g.onAbort)g.onAbort(a);k(a);sa=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function Na(){return G.startsWith("data:application/octet-stream;base64,")}var G;G="thing.wasm";
if(!Na()){var Qa=G;G=g.locateFile?g.locateFile(Qa,w):w+Qa}function Ra(){var a=G;try{if(a==G&&qa)return new Uint8Array(qa);if(ka)return ka(a);throw"both async and sync fetching of the wasm failed";}catch(b){y(b)}}
function Sa(){if(!qa&&(ea||fa)){if("function"===typeof fetch&&!G.startsWith("file://"))return fetch(G,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+G+"'";return a.arrayBuffer()}).catch(function(){return Ra()});if(ja)return new Promise(function(a,b){ja(G,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Ra()})}var H,I;
function Ta(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(g);else{var c=b.Nb;"number"===typeof c?void 0===b.Xa?Da.get(c)():Da.get(c)(b.Xa):c(void 0===b.Xa?null:b.Xa)}}}
function Ua(){function a(h){return(h=h.toTimeString().match(/\(([A-Za-z ]+)\)$/))?h[1]:"GMT"}var b=(new Date).getFullYear(),c=new Date(b,0,1),d=new Date(b,6,1);b=c.getTimezoneOffset();var e=d.getTimezoneOffset(),f=Math.max(b,e);E[Va()>>2]=60*f;E[Wa()>>2]=Number(b!=e);c=a(c);d=a(d);c=xa(c);d=xa(d);e<b?(E[Xa()>>2]=c,E[Xa()+4>>2]=d):(E[Xa()>>2]=d,E[Xa()+4>>2]=c)}var Ya;
function Za(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function J(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Za(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function $a(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function ab(a){if("/"===a)return"/";a=J(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function bb(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(ha)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){y("randomDevice")}}
function cb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Za(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}
function db(a,b){function c(h){for(var n=0;n<h.length&&""===h[n];n++);for(var m=h.length-1;0<=m&&""===h[m];m--);return n>m?[]:h.slice(n,m-n+1)}a=cb(a).substr(1);b=cb(b).substr(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),e=d,f=0;f<d;f++)if(a[f]!==b[f]){e=f;break}d=[];for(f=e;f<a.length;f++)d.push("..");d=d.concat(b.slice(e));return d.join("/")}var eb=[];function fb(a,b){eb[a]={input:[],output:[],La:b};gb(a,hb)}
var hb={open:function(a){var b=eb[a.node.rdev];if(!b)throw new L(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.La.flush(a.tty)},flush:function(a){a.tty.La.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.La.kb)throw new L(60);for(var e=0,f=0;f<d;f++){try{var h=a.tty.La.kb(a.tty)}catch(n){throw new L(29);}if(void 0===h&&0===e)throw new L(6);if(null===h||void 0===h)break;e++;b[c+f]=h}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.La.ab)throw new L(60);
try{for(var e=0;e<d;e++)a.tty.La.ab(a.tty,b[c+e])}catch(f){throw new L(29);}d&&(a.node.timestamp=Date.now());return e}},jb={kb:function(a){if(!a.input.length){var b=null;if(ha){var c=Buffer.alloc(256),d=0;try{d=la.readSync(process.stdin.fd,c,0,256,null)}catch(e){if(e.toString().includes("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=
readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=ib(b)}return a.input.shift()},ab:function(a,b){null===b||10===b?(pa(ua(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(pa(ua(a.output,0)),a.output=[])}},kb={ab:function(a,b){null===b||10===b?(k(ua(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(k(ua(a.output,0)),a.output=[])}},M={Ea:null,ua:function(){return M.createNode(null,"/",16895,0)},createNode:function(a,
b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new L(63);M.Ea||(M.Ea={dir:{node:{Ba:M.la.Ba,wa:M.la.wa,lookup:M.la.lookup,Va:M.la.Va,rename:M.la.rename,unlink:M.la.unlink,rmdir:M.la.rmdir,readdir:M.la.readdir,symlink:M.la.symlink},stream:{Ha:M.ma.Ha}},file:{node:{Ba:M.la.Ba,wa:M.la.wa},stream:{Ha:M.ma.Ha,read:M.ma.read,write:M.ma.write,fb:M.ma.fb,nb:M.ma.nb,pb:M.ma.pb}},link:{node:{Ba:M.la.Ba,wa:M.la.wa,readlink:M.la.readlink},stream:{}},hb:{node:{Ba:M.la.Ba,wa:M.la.wa},stream:lb}});c=mb(a,b,
c,d);N(c.mode)?(c.la=M.Ea.dir.node,c.ma=M.Ea.dir.stream,c.na={}):32768===(c.mode&61440)?(c.la=M.Ea.file.node,c.ma=M.Ea.file.stream,c.pa=0,c.na=null):40960===(c.mode&61440)?(c.la=M.Ea.link.node,c.ma=M.Ea.link.stream):8192===(c.mode&61440)&&(c.la=M.Ea.hb.node,c.ma=M.Ea.hb.stream);c.timestamp=Date.now();a&&(a.na[b]=c,a.timestamp=c.timestamp);return c},Ob:function(a){return a.na?a.na.subarray?a.na.subarray(0,a.pa):new Uint8Array(a.na):new Uint8Array(0)},ib:function(a,b){var c=a.na?a.na.length:0;c>=b||
(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.na,a.na=new Uint8Array(b),0<a.pa&&a.na.set(c.subarray(0,a.pa),0))},Gb:function(a,b){if(a.pa!=b)if(0==b)a.na=null,a.pa=0;else{var c=a.na;a.na=new Uint8Array(b);c&&a.na.set(c.subarray(0,Math.min(b,a.pa)));a.pa=b}},la:{Ba:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;N(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.pa:40960===(a.mode&61440)?b.size=a.link.length:
b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.xb=4096;b.blocks=Math.ceil(b.size/b.xb);return b},wa:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&M.Gb(a,b.size)},lookup:function(){throw nb[44];},Va:function(a,b,c,d){return M.createNode(a,b,c,d)},rename:function(a,b,c){if(N(a.mode)){try{var d=O(b,c)}catch(f){}if(d)for(var e in d.na)throw new L(55);}delete a.parent.na[a.name];a.parent.timestamp=
Date.now();a.name=c;b.na[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink:function(a,b){delete a.na[b];a.timestamp=Date.now()},rmdir:function(a,b){var c=O(a,b),d;for(d in c.na)throw new L(55);delete a.na[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.na)a.na.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=M.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new L(28);return a.link}},ma:{read:function(a,
b,c,d,e){var f=a.node.na;if(e>=a.node.pa)return 0;a=Math.min(a.node.pa-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.na||a.na.subarray)){if(f)return a.na=b.subarray(c,c+d),a.pa=d;if(0===a.pa&&0===e)return a.na=b.slice(c,c+d),a.pa=d;if(e+d<=a.pa)return a.na.set(b.subarray(c,c+d),e),d}M.ib(a,e+d);if(a.na.subarray&&b.subarray)a.na.set(b.subarray(c,c+d),e);else for(f=
0;f<d;f++)a.na[e+f]=b[c+f];a.pa=Math.max(a.pa,e+d);return d},Ha:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.pa);if(0>b)throw new L(28);return b},fb:function(a,b,c){M.ib(a.node,b+c);a.node.pa=Math.max(a.node.pa,b+c)},nb:function(a,b,c,d,e,f){if(0!==b)throw new L(28);if(32768!==(a.node.mode&61440))throw new L(43);a=a.node.na;if(f&2||a.buffer!==Aa){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;y();c=void 0;if(!c)throw new L(48);
C.set(a,c)}else d=!1,c=a.byteOffset;return{Sb:c,Kb:d}},pb:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new L(43);if(e&2)return 0;M.ma.write(a,b,0,d,c,!1);return 0}}};function ob(a,b,c){var d="al "+a;ja(a,function(e){assert(e,'Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(e));d&&Ma(d)},function(){if(c)c();else throw'Loading data file "'+a+'" failed.';});d&&La(d)}var pb=null,qb={},P=[],rb=1,Q=null,sb=!0,L=null,nb={};
function R(a,b){a=cb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={jb:!0,bb:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.bb)throw new L(32);a=Za(a.split("/").filter(function(h){return!!h}),!1);var e=pb;c="/";for(d=0;d<a.length;d++){var f=d===a.length-1;if(f&&b.parent)break;e=O(e,a[d]);c=J(c+"/"+a[d]);e.Fa&&(!f||f&&b.jb)&&(e=e.Fa.root);if(!f||b.Ja)for(f=0;40960===(e.mode&61440);)if(e=tb(c),c=cb($a(c),e),e=R(c,{bb:b.bb}).node,40<f++)throw new L(32);}return{path:c,node:e}}
function S(a){for(var b;;){if(a===a.parent)return a=a.ua.ob,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function ub(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Q.length}function vb(a){var b=ub(a.parent.id,a.name);a.Ka=Q[b];Q[b]=a}function wb(a){var b=ub(a.parent.id,a.name);if(Q[b]===a)Q[b]=a.Ka;else for(b=Q[b];b;){if(b.Ka===a){b.Ka=a.Ka;break}b=b.Ka}}
function O(a,b){var c;if(c=(c=xb(a,"x"))?c:a.la.lookup?0:2)throw new L(c,a);for(c=Q[ub(a.id,b)];c;c=c.Ka){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.la.lookup(a,b)}function mb(a,b,c,d){a=new yb(a,b,c,d);vb(a);return a}function N(a){return 16384===(a&61440)}var Ab={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090};function Bb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}
function xb(a,b){if(sb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Cb(a,b){try{return O(a,b),20}catch(c){}return xb(a,"wx")}function Db(a,b,c){try{var d=O(a,b)}catch(e){return e.oa}if(a=xb(a,"wx"))return a;if(c){if(!N(d.mode))return 54;if(d===d.parent||"/"===S(d))return 10}else if(N(d.mode))return 31;return 0}function Eb(a,b){b=b||4096;for(a=a||0;a<=b;a++)if(!P[a])return a;throw new L(33);}
function Fb(a,b,c){Gb||(Gb=function(){},Gb.prototype={});var d=new Gb,e;for(e in a)d[e]=a[e];a=d;b=Eb(b,c);a.fd=b;return P[b]=a}var lb={open:function(a){a.ma=qb[a.node.rdev].ma;a.ma.open&&a.ma.open(a)},Ha:function(){throw new L(70);}};function gb(a,b){qb[a]={ma:b}}
function Hb(a,b){var c="/"===b,d=!b;if(c&&pb)throw new L(10);if(!c&&!d){var e=R(b,{jb:!1});b=e.path;e=e.node;if(e.Fa)throw new L(10);if(!N(e.mode))throw new L(54);}b={type:a,Rb:{},ob:b,Db:[]};a=a.ua(b);a.ua=b;b.root=a;c?pb=a:e&&(e.Fa=b,e.ua&&e.ua.Db.push(b));return a}function Ib(a,b,c){var d=R(a,{parent:!0}).node;a=ab(a);if(!a||"."===a||".."===a)throw new L(28);var e=Cb(d,a);if(e)throw new L(e);if(!d.la.Va)throw new L(63);return d.la.Va(d,a,b,c)}
function T(a,b){return Ib(a,(void 0!==b?b:511)&1023|16384,0)}function Jb(a,b,c){"undefined"===typeof c&&(c=b,b=438);return Ib(a,b|8192,c)}function Kb(a,b){if(!cb(a))throw new L(44);var c=R(b,{parent:!0}).node;if(!c)throw new L(44);b=ab(b);var d=Cb(c,b);if(d)throw new L(d);if(!c.la.symlink)throw new L(63);c.la.symlink(c,b,a)}
function Lb(a){var b=R(a,{parent:!0}).node;a=ab(a);var c=O(b,a),d=Db(b,a,!1);if(d)throw new L(d);if(!b.la.unlink)throw new L(63);if(c.Fa)throw new L(10);b.la.unlink(b,a);wb(c)}function tb(a){a=R(a).node;if(!a)throw new L(44);if(!a.la.readlink)throw new L(28);return cb(S(a.parent),a.la.readlink(a))}function Mb(a,b){a=R(a,{Ja:!b}).node;if(!a)throw new L(44);if(!a.la.Ba)throw new L(63);return a.la.Ba(a)}function Nb(a){return Mb(a,!0)}
function Ob(a,b){a="string"===typeof a?R(a,{Ja:!0}).node:a;if(!a.la.wa)throw new L(63);a.la.wa(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})}
function Pb(a,b,c,d,e){if(""===a)throw new L(44);if("string"===typeof b){var f=Ab[b];if("undefined"===typeof f)throw Error("Unknown file open mode: "+b);b=f}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var h=a;else{a=J(a);try{h=R(a,{Ja:!(b&131072)}).node}catch(n){}}f=!1;if(b&64)if(h){if(b&128)throw new L(20);}else h=Ib(a,c,0),f=!0;if(!h)throw new L(44);8192===(h.mode&61440)&&(b&=-513);if(b&65536&&!N(h.mode))throw new L(54);if(!f&&(c=h?40960===(h.mode&61440)?32:N(h.mode)&&
("r"!==Bb(b)||b&512)?31:xb(h,Bb(b)):44))throw new L(c);if(b&512){c=h;c="string"===typeof c?R(c,{Ja:!0}).node:c;if(!c.la.wa)throw new L(63);if(N(c.mode))throw new L(31);if(32768!==(c.mode&61440))throw new L(28);if(f=xb(c,"w"))throw new L(f);c.la.wa(c,{size:0,timestamp:Date.now()})}b&=-131713;d=Fb({node:h,path:S(h),flags:b,seekable:!0,position:0,ma:h.ma,Ib:[],error:!1},d,e);d.ma.open&&d.ma.open(d);!g.logReadFiles||b&1||(Qb||(Qb={}),a in Qb||(Qb[a]=1));return d}
function Rb(a){if(null===a.fd)throw new L(8);a.Ga&&(a.Ga=null);try{a.ma.close&&a.ma.close(a)}catch(b){throw b;}finally{P[a.fd]=null}a.fd=null}function Sb(a,b,c){if(null===a.fd)throw new L(8);if(!a.seekable||!a.ma.Ha)throw new L(70);if(0!=c&&1!=c&&2!=c)throw new L(28);a.position=a.ma.Ha(a,b,c);a.Ib=[];return a.position}
function Tb(a,b,c,d,e,f){if(0>d||0>e)throw new L(28);if(null===a.fd)throw new L(8);if(0===(a.flags&2097155))throw new L(8);if(N(a.node.mode))throw new L(31);if(!a.ma.write)throw new L(28);a.seekable&&a.flags&1024&&Sb(a,0,2);var h="undefined"!==typeof e;if(!h)e=a.position;else if(!a.seekable)throw new L(70);b=a.ma.write(a,b,c,d,e,f);h||(a.position+=b);return b}
function Ub(){L||(L=function(a,b){this.node=b;this.Hb=function(c){this.oa=c};this.Hb(a);this.message="FS error"},L.prototype=Error(),L.prototype.constructor=L,[44].forEach(function(a){nb[a]=new L(a);nb[a].stack="<generic error, no stack>"}))}var Vb;function Wb(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}function Xb(a,b){a="string"===typeof a?a:S(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=J(a+"/"+c);try{T(d)}catch(e){}a=d}}return d}
function Yb(a,b,c,d){a=J(("string"===typeof a?a:S(a))+"/"+b);c=Wb(c,d);return Ib(a,(void 0!==c?c:438)&4095|32768,0)}function Zb(a,b,c,d,e,f){a=b?J(("string"===typeof a?a:S(a))+"/"+b):a;d=Wb(d,e);e=Ib(a,(void 0!==d?d:438)&4095|32768,0);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var h=c.length;b<h;++b)a[b]=c.charCodeAt(b);c=a}Ob(e,d|146);a=Pb(e,577);Tb(a,c,0,c.length,0,f);Rb(a);Ob(e,d)}return e}
function U(a,b,c,d){a=J(("string"===typeof a?a:S(a))+"/"+b);b=Wb(!!c,!!d);U.mb||(U.mb=64);var e=U.mb++<<8|0;gb(e,{open:function(f){f.seekable=!1},close:function(){d&&d.buffer&&d.buffer.length&&d(10)},read:function(f,h,n,m){for(var t=0,p=0;p<m;p++){try{var r=c()}catch(q){throw new L(29);}if(void 0===r&&0===t)throw new L(6);if(null===r||void 0===r)break;t++;h[n+p]=r}t&&(f.node.timestamp=Date.now());return t},write:function(f,h,n,m){for(var t=0;t<m;t++)try{d(h[n+t])}catch(p){throw new L(29);}m&&(f.node.timestamp=
Date.now());return t}});return Jb(a,b,e)}function $b(a){if(!(a.Bb||a.Cb||a.link||a.na)){if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(ia)try{a.na=ib(ia(a.url)),a.pa=a.na.length}catch(b){throw new L(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}}
function ac(a,b,c,d,e){function f(){this.Za=!1;this.Ca=[]}f.prototype.get=function(p){if(!(p>this.length-1||0>p)){var r=p%this.chunkSize;return this.lb(p/this.chunkSize|0)[r]}};f.prototype.$a=function(p){this.lb=p};f.prototype.gb=function(){var p=new XMLHttpRequest;p.open("HEAD",c,!1);p.send(null);if(!(200<=p.status&&300>p.status||304===p.status))throw Error("Couldn't load "+c+". Status: "+p.status);var r=Number(p.getResponseHeader("Content-length")),q,u=(q=p.getResponseHeader("Accept-Ranges"))&&
"bytes"===q;p=(q=p.getResponseHeader("Content-Encoding"))&&"gzip"===q;var x=1048576;u||(x=r);var v=this;v.$a(function(D){var F=D*x,ba=(D+1)*x-1;ba=Math.min(ba,r-1);if("undefined"===typeof v.Ca[D]){var K=v.Ca;if(F>ba)throw Error("invalid range ("+F+", "+ba+") or no bytes requested!");if(ba>r-1)throw Error("only "+r+" bytes available! programmer error!");var B=new XMLHttpRequest;B.open("GET",c,!1);r!==x&&B.setRequestHeader("Range","bytes="+F+"-"+ba);"undefined"!=typeof Uint8Array&&(B.responseType="arraybuffer");
B.overrideMimeType&&B.overrideMimeType("text/plain; charset=x-user-defined");B.send(null);if(!(200<=B.status&&300>B.status||304===B.status))throw Error("Couldn't load "+c+". Status: "+B.status);F=void 0!==B.response?new Uint8Array(B.response||[]):ib(B.responseText||"");K[D]=F}if("undefined"===typeof v.Ca[D])throw Error("doXHR failed!");return v.Ca[D]});if(p||!r)x=r=1,x=r=this.lb(0).length,pa("LazyFiles on gzip forces download of the whole file when length is accessed");this.wb=r;this.vb=x;this.Za=
!0};if("undefined"!==typeof XMLHttpRequest){if(!fa)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var h=new f;Object.defineProperties(h,{length:{get:function(){this.Za||this.gb();return this.wb}},chunkSize:{get:function(){this.Za||this.gb();return this.vb}}});var n=void 0}else n=c,h=void 0;var m=Yb(a,b,d,e);h?m.na=h:n&&(m.na=null,m.url=n);Object.defineProperties(m,{pa:{get:function(){return this.na.length}}});var t={};Object.keys(m.ma).forEach(function(p){var r=
m.ma[p];t[p]=function(){$b(m);return r.apply(null,arguments)}});t.read=function(p,r,q,u,x){$b(m);p=p.node.na;if(x>=p.length)return 0;u=Math.min(p.length-x,u);if(p.slice)for(var v=0;v<u;v++)r[q+v]=p[x+v];else for(v=0;v<u;v++)r[q+v]=p.get(x+v);return u};m.ma=t;return m}
function bc(a,b,c,d,e,f,h,n,m,t){function p(u){function x(D){t&&t();n||Zb(a,b,D,d,e,m);f&&f();Ma(q)}var v=!1;g.preloadPlugins.forEach(function(D){!v&&D.canHandle(r)&&(D.handle(u,r,x,function(){h&&h();Ma(q)}),v=!0)});v||x(u)}cc.Qb();var r=b?cb(J(a+"/"+b)):a,q="cp "+r;La(q);"string"==typeof c?ob(c,function(u){p(u)},h):p(c)}var V={},Gb,Qb;
function dc(a,b,c){try{var d=a(b)}catch(e){if(e&&e.node&&J(b)!==J(S(e.node)))return-54;throw e;}E[c>>2]=d.dev;E[c+4>>2]=0;E[c+8>>2]=d.ino;E[c+12>>2]=d.mode;E[c+16>>2]=d.nlink;E[c+20>>2]=d.uid;E[c+24>>2]=d.gid;E[c+28>>2]=d.rdev;E[c+32>>2]=0;I=[d.size>>>0,(H=d.size,1<=+Math.abs(H)?0<H?(Math.min(+Math.floor(H/4294967296),4294967295)|0)>>>0:~~+Math.ceil((H-+(~~H>>>0))/4294967296)>>>0:0)];E[c+40>>2]=I[0];E[c+44>>2]=I[1];E[c+48>>2]=4096;E[c+52>>2]=d.blocks;E[c+56>>2]=d.atime.getTime()/1E3|0;E[c+60>>2]=
0;E[c+64>>2]=d.mtime.getTime()/1E3|0;E[c+68>>2]=0;E[c+72>>2]=d.ctime.getTime()/1E3|0;E[c+76>>2]=0;I=[d.ino>>>0,(H=d.ino,1<=+Math.abs(H)?0<H?(Math.min(+Math.floor(H/4294967296),4294967295)|0)>>>0:~~+Math.ceil((H-+(~~H>>>0))/4294967296)>>>0:0)];E[c+80>>2]=I[0];E[c+84>>2]=I[1];return 0}var ec=void 0;function fc(){ec+=4;return E[ec-4>>2]}function W(a){a=P[a];if(!a)throw new L(8);return a}
var X={ua:function(){g.websocket=g.websocket&&"object"===typeof g.websocket?g.websocket:{};g.websocket.Wa={};g.websocket.on=function(a,b){"function"===typeof b&&(this.Wa[a]=b);return this};g.websocket.emit=function(a,b){"function"===typeof this.Wa[a]&&this.Wa[a].call(this,b)};return mb(null,"/",16895,0)},createSocket:function(a,b,c){b&=-526337;c&&assert(1==b==(6==c));a={family:a,type:b,protocol:c,sa:null,error:null,Qa:{},pending:[],Ma:[],xa:X.ta};b=X.Da();c=mb(X.root,b,49152,0);c.Na=a;b=Fb({path:b,
node:c,flags:2,seekable:!1,ma:X.ma});a.stream=b;return a},zb:function(a){return(a=P[a])&&49152===(a.node.mode&49152)?a.node.Na:null},ma:{Ra:function(a){a=a.node.Na;return a.xa.Ra(a)},Pa:function(a,b,c){a=a.node.Na;return a.xa.Pa(a,b,c)},read:function(a,b,c,d){a=a.node.Na;d=a.xa.rb(a,d);if(!d)return 0;b.set(d.buffer,c);return d.buffer.length},write:function(a,b,c,d){a=a.node.Na;return a.xa.ub(a,b,c,d)},close:function(a){a=a.node.Na;a.xa.close(a)}},Da:function(){X.Da.current||(X.Da.current=0);return"socket["+
X.Da.current++ +"]"},ta:{Sa:function(a,b,c){if("object"===typeof b){var d=b;c=b=null}if(d)if(d._socket)b=d._socket.remoteAddress,c=d._socket.remotePort;else{c=/ws[s]?:\/\/([^:]+):(\d+)/.exec(d.url);if(!c)throw Error("WebSocket URL must be in the format ws(s)://address:port");b=c[1];c=parseInt(c[2],10)}else try{var e=g.websocket&&"object"===typeof g.websocket,f="ws://";e&&"string"===typeof g.websocket.url&&(f=g.websocket.url);if("ws://"===f||"wss://"===f){var h=b.split("/");f=f+h[0]+":"+c+"/"+h.slice(1).join("/")}h=
"binary";e&&"string"===typeof g.websocket.subprotocol&&(h=g.websocket.subprotocol);var n=void 0;"null"!==h&&(h=h.replace(/^ +| +$/g,"").split(/ *, */),n=ha?{protocol:h.toString()}:h);e&&null===g.websocket.subprotocol&&(n=void 0);d=new (ha?require("ws"):WebSocket)(f,n);d.binaryType="arraybuffer"}catch(m){throw new L(23);}b={ra:b,port:c,socket:d,Ta:[]};X.ta.eb(a,b);X.ta.Ab(a,b);2===a.type&&"undefined"!==typeof a.Oa&&b.Ta.push(new Uint8Array([255,255,255,255,112,111,114,116,(a.Oa&65280)>>8,a.Oa&255]));
return b},Ua:function(a,b,c){return a.Qa[b+":"+c]},eb:function(a,b){a.Qa[b.ra+":"+b.port]=b},tb:function(a,b){delete a.Qa[b.ra+":"+b.port]},Ab:function(a,b){function c(){g.websocket.emit("open",a.stream.fd);try{for(var f=b.Ta.shift();f;)b.socket.send(f),f=b.Ta.shift()}catch(h){b.socket.close()}}function d(f){if("string"===typeof f)f=(new TextEncoder).encode(f);else{assert(void 0!==f.byteLength);if(0==f.byteLength)return;f=new Uint8Array(f)}var h=e;e=!1;h&&10===f.length&&255===f[0]&&255===f[1]&&255===
f[2]&&255===f[3]&&112===f[4]&&111===f[5]&&114===f[6]&&116===f[7]?(f=f[8]<<8|f[9],X.ta.tb(a,b),b.port=f,X.ta.eb(a,b)):(a.Ma.push({ra:b.ra,port:b.port,data:f}),g.websocket.emit("message",a.stream.fd))}var e=!0;ha?(b.socket.on("open",c),b.socket.on("message",function(f,h){h.Lb&&d((new Uint8Array(f)).buffer)}),b.socket.on("close",function(){g.websocket.emit("close",a.stream.fd)}),b.socket.on("error",function(){a.error=14;g.websocket.emit("error",[a.stream.fd,a.error,"ECONNREFUSED: Connection refused"])})):
(b.socket.onopen=c,b.socket.onclose=function(){g.websocket.emit("close",a.stream.fd)},b.socket.onmessage=function(f){d(f.data)},b.socket.onerror=function(){a.error=14;g.websocket.emit("error",[a.stream.fd,a.error,"ECONNREFUSED: Connection refused"])})},Ra:function(a){if(1===a.type&&a.sa)return a.pending.length?65:0;var b=0,c=1===a.type?X.ta.Ua(a,a.va,a.za):null;if(a.Ma.length||!c||c&&c.socket.readyState===c.socket.CLOSING||c&&c.socket.readyState===c.socket.CLOSED)b|=65;if(!c||c&&c.socket.readyState===
c.socket.OPEN)b|=4;if(c&&c.socket.readyState===c.socket.CLOSING||c&&c.socket.readyState===c.socket.CLOSED)b|=16;return b},Pa:function(a,b,c){switch(b){case 21531:return b=0,a.Ma.length&&(b=a.Ma[0].data.length),E[c>>2]=b,0;default:return 28}},close:function(a){if(a.sa){try{a.sa.close()}catch(e){}a.sa=null}for(var b=Object.keys(a.Qa),c=0;c<b.length;c++){var d=a.Qa[b[c]];try{d.socket.close()}catch(e){}X.ta.tb(a,d)}return 0},bind:function(a,b,c){if("undefined"!==typeof a.cb||"undefined"!==typeof a.Oa)throw new L(28);
a.cb=b;a.Oa=c;if(2===a.type){a.sa&&(a.sa.close(),a.sa=null);try{a.xa.listen(a,0)}catch(d){if(!(d instanceof L))throw d;if(138!==d.oa)throw d;}}},connect:function(a,b,c){if(a.sa)throw new L(138);if("undefined"!==typeof a.va&&"undefined"!==typeof a.za){var d=X.ta.Ua(a,a.va,a.za);if(d){if(d.socket.readyState===d.socket.CONNECTING)throw new L(7);throw new L(30);}}b=X.ta.Sa(a,b,c);a.va=b.ra;a.za=b.port;throw new L(26);},listen:function(a){if(!ha)throw new L(138);if(a.sa)throw new L(28);var b=require("ws").Server;
a.sa=new b({host:a.cb,port:a.Oa});g.websocket.emit("listen",a.stream.fd);a.sa.on("connection",function(c){if(1===a.type){var d=X.createSocket(a.family,a.type,a.protocol);c=X.ta.Sa(d,c);d.va=c.ra;d.za=c.port;a.pending.push(d);g.websocket.emit("connection",d.stream.fd)}else X.ta.Sa(a,c),g.websocket.emit("connection",a.stream.fd)});a.sa.on("closed",function(){g.websocket.emit("close",a.stream.fd);a.sa=null});a.sa.on("error",function(){a.error=23;g.websocket.emit("error",[a.stream.fd,a.error,"EHOSTUNREACH: Host is unreachable"])})},
accept:function(a){if(!a.sa)throw new L(28);var b=a.pending.shift();b.stream.flags=a.stream.flags;return b},Pb:function(a,b){if(b){if(void 0===a.va||void 0===a.za)throw new L(53);b=a.va;a=a.za}else b=a.cb||0,a=a.Oa||0;return{ra:b,port:a}},ub:function(a,b,c,d,e,f){if(2===a.type){if(void 0===e||void 0===f)e=a.va,f=a.za;if(void 0===e||void 0===f)throw new L(17);}else e=a.va,f=a.za;var h=X.ta.Ua(a,e,f);if(1===a.type){if(!h||h.socket.readyState===h.socket.CLOSING||h.socket.readyState===h.socket.CLOSED)throw new L(53);
if(h.socket.readyState===h.socket.CONNECTING)throw new L(6);}ArrayBuffer.isView(b)&&(c+=b.byteOffset,b=b.buffer);b=b.slice(c,c+d);if(2===a.type&&(!h||h.socket.readyState!==h.socket.OPEN))return h&&h.socket.readyState!==h.socket.CLOSING&&h.socket.readyState!==h.socket.CLOSED||(h=X.ta.Sa(a,e,f)),h.Ta.push(b),d;try{return h.socket.send(b),d}catch(n){throw new L(28);}},rb:function(a,b){if(1===a.type&&a.sa)throw new L(53);var c=a.Ma.shift();if(!c){if(1===a.type){if(a=X.ta.Ua(a,a.va,a.za)){if(a.socket.readyState===
a.socket.CLOSING||a.socket.readyState===a.socket.CLOSED)return null;throw new L(6);}throw new L(53);}throw new L(6);}var d=c.data.byteLength||c.data.length,e=c.data.byteOffset||0,f=c.data.buffer||c.data;b=Math.min(b,d);var h={buffer:new Uint8Array(f,e,b),ra:c.ra,port:c.port};1===a.type&&b<d&&(c.data=new Uint8Array(f,e+b,d-b),a.Ma.unshift(c));return h}}};function gc(a){a=X.zb(a);if(!a)throw new L(8);return a}
function hc(a){a=a.split(".");for(var b=0;4>b;b++){var c=Number(a[b]);if(isNaN(c))return null;a[b]=c}return(a[0]|a[1]<<8|a[2]<<16|a[3]<<24)>>>0}
function ic(a){var b,c,d=[];if(!/^((?=.*::)(?!.*::.+::)(::)?([\dA-F]{1,4}:(:|\b)|){5}|([\dA-F]{1,4}:){6})((([\dA-F]{1,4}((?!\3)::|:\b|$))|(?!\2\3)){2}|(((2[0-4]|1\d|[1-9])?\d|25[0-5])\.?\b){4})$/i.test(a))return null;if("::"===a)return[0,0,0,0,0,0,0,0];a=a.startsWith("::")?a.replace("::","Z:"):a.replace("::",":Z:");0<a.indexOf(".")?(a=a.replace(RegExp("[.]","g"),":"),a=a.split(":"),a[a.length-4]=parseInt(a[a.length-4])+256*parseInt(a[a.length-3]),a[a.length-3]=parseInt(a[a.length-2])+256*parseInt(a[a.length-
1]),a=a.slice(0,a.length-2)):a=a.split(":");for(b=c=0;b<a.length;b++)if("string"===typeof a[b])if("Z"===a[b]){for(c=0;c<8-a.length+1;c++)d[b+c]=0;--c}else d[b+c]=jc(parseInt(a[b],16));else d[b+c]=a[b];return[d[1]<<16|d[0],d[3]<<16|d[2],d[5]<<16|d[4],d[7]<<16|d[6]]}
function kc(a,b,c,d,e){switch(b){case 2:c=hc(c);A.fill(0,a,a+16);e&&(E[e>>2]=16);Ba[a>>1]=b;E[a+4>>2]=c;Ba[a+2>>1]=jc(d);break;case 10:c=ic(c);A.fill(0,a,a+28);e&&(E[e>>2]=28);E[a>>2]=b;E[a+8>>2]=c[0];E[a+12>>2]=c[1];E[a+16>>2]=c[2];E[a+20>>2]=c[3];Ba[a+2>>1]=jc(d);break;default:return 5}return 0}var lc=1,mc={},nc={};
function oc(a){var b=hc(a);if(null!==b)return a;b=ic(a);if(null!==b)return a;mc[a]?b=mc[a]:(b=lc++,assert(65535>b,"exceeded max address mappings of 65535"),b="172.29."+(b&255)+"."+(b&65280),nc[b]=a,mc[a]=b);return b}function pc(a){return(a&255)+"."+(a>>8&255)+"."+(a>>16&255)+"."+(a>>24&255)}
function qc(a){var b="",c,d=0,e=0,f=0,h=0;a=[a[0]&65535,a[0]>>16,a[1]&65535,a[1]>>16,a[2]&65535,a[2]>>16,a[3]&65535,a[3]>>16];var n=!0;for(c=0;5>c;c++)if(0!==a[c]){n=!1;break}if(n){c=pc(a[6]|a[7]<<16);if(-1===a[5])return"::ffff:"+c;if(0===a[5])return"0.0.0.0"===c&&(c=""),"0.0.0.1"===c&&(c="1"),"::"+c}for(c=0;8>c;c++)0===a[c]&&(1<c-e&&(h=0),e=c,h++),h>d&&(d=h,f=c-d+1);for(c=0;8>c;c++)1<d&&0===a[c]&&c>=f&&c<f+d?c===f&&(b+=":",0===f&&(b+=":")):(b+=Number(rc(a[c]&65535)).toString(16),b+=7>c?":":"");return b}
function sc(a,b){var c=Ba[a>>1],d=rc(Ca[a+2>>1]);switch(c){case 2:if(16!==b)return{oa:28};a=E[a+4>>2];a=pc(a);break;case 10:if(28!==b)return{oa:28};a=[E[a+8>>2],E[a+12>>2],E[a+16>>2],E[a+20>>2]];a=qc(a);break;default:return{oa:5}}return{family:c,ra:a,port:d}}function tc(a,b,c){if(c&&0===a)return null;a=sc(a,b);if(a.oa)throw new L(a.oa);b=a.ra;a.ra=(nc[b]?nc[b]:null)||a.ra;return a}
var Y={ya:8192,ua:function(){return mb(null,"/",16895,0)},yb:function(){var a={qa:[],sb:2};a.qa.push({buffer:new Uint8Array(Y.ya),offset:0,Aa:0});var b=Y.Da(),c=Y.Da(),d=mb(Y.root,b,4096,0),e=mb(Y.root,c,4096,0);d.pipe=a;e.pipe=a;a=Fb({path:b,node:d,flags:0,seekable:!1,ma:Y.ma});d.stream=a;c=Fb({path:c,node:e,flags:1,seekable:!1,ma:Y.ma});e.stream=c;return{Fb:a.fd,Jb:c.fd}},ma:{Ra:function(a){var b=a.node.pipe;if(1===(a.flags&2097155))return 260;if(0<b.qa.length)for(a=0;a<b.qa.length;a++){var c=b.qa[a];
if(0<c.offset-c.Aa)return 65}return 0},Pa:function(){return 28},fsync:function(){return 28},read:function(a,b,c,d){a=a.node.pipe;for(var e=0,f=0;f<a.qa.length;f++){var h=a.qa[f];e+=h.offset-h.Aa}assert(b instanceof ArrayBuffer||ArrayBuffer.isView(b));b=b.subarray(c,c+d);if(0>=d)return 0;if(0==e)throw new L(6);c=d=Math.min(e,d);for(f=e=0;f<a.qa.length;f++){h=a.qa[f];var n=h.offset-h.Aa;if(d<=n){var m=h.buffer.subarray(h.Aa,h.offset);d<n?(m=m.subarray(0,d),h.Aa+=d):e++;b.set(m);break}else m=h.buffer.subarray(h.Aa,
h.offset),b.set(m),b=b.subarray(m.byteLength),d-=m.byteLength,e++}e&&e==a.qa.length&&(e--,a.qa[e].offset=0,a.qa[e].Aa=0);a.qa.splice(0,e);return c},write:function(a,b,c,d){a=a.node.pipe;assert(b instanceof ArrayBuffer||ArrayBuffer.isView(b));b=b.subarray(c,c+d);c=b.byteLength;if(0>=c)return 0;0==a.qa.length?(d={buffer:new Uint8Array(Y.ya),offset:0,Aa:0},a.qa.push(d)):d=a.qa[a.qa.length-1];assert(d.offset<=Y.ya);var e=Y.ya-d.offset;if(e>=c)return d.buffer.set(b,d.offset),d.offset+=c,c;0<e&&(d.buffer.set(b.subarray(0,
e),d.offset),d.offset+=e,b=b.subarray(e,b.byteLength));d=b.byteLength/Y.ya|0;e=b.byteLength%Y.ya;for(var f=0;f<d;f++){var h={buffer:new Uint8Array(Y.ya),offset:Y.ya,Aa:0};a.qa.push(h);h.buffer.set(b.subarray(0,Y.ya));b=b.subarray(Y.ya,b.byteLength)}0<e&&(h={buffer:new Uint8Array(Y.ya),offset:b.byteLength,Aa:0},a.qa.push(h),h.buffer.set(b));return c},close:function(a){a=a.node.pipe;a.sb--;0===a.sb&&(a.qa=null)}},Da:function(){Y.Da.current||(Y.Da.current=0);return"pipe["+Y.Da.current++ +"]"}},uc={};
function vc(){if(!wc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ca||"./this.program"},b;for(b in uc)void 0===uc[b]?delete a[b]:a[b]=uc[b];var c=[];for(b in a)c.push(b+"="+a[b]);wc=c}return wc}var wc,Z={};
function xc(a){xc.buffer||(xc.buffer=ya(256),Z["0"]="Success",Z["-1"]="Invalid value for 'ai_flags' field",Z["-2"]="NAME or SERVICE is unknown",Z["-3"]="Temporary failure in name resolution",Z["-4"]="Non-recoverable failure in name res",Z["-6"]="'ai_family' not supported",Z["-7"]="'ai_socktype' not supported",Z["-8"]="SERVICE not supported for 'ai_socktype'",Z["-10"]="Memory allocation failure",Z["-11"]="System error returned in 'errno'",Z["-12"]="Argument buffer overflow");var b="Unknown error";
a in Z&&(255<Z[a].length?b="Message too long":b=Z[a]);za(b,xc.buffer);return xc.buffer}function yb(a,b,c,d){a||(a=this);this.parent=a;this.ua=a.ua;this.Fa=null;this.id=rb++;this.name=b;this.mode=c;this.la={};this.ma={};this.rdev=d}
Object.defineProperties(yb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Cb:{get:function(){return N(this.mode)}},Bb:{get:function(){return 8192===(this.mode&61440)}}});Ub();Q=Array(4096);Hb(M,"/");T("/tmp");T("/home");T("/home/web_user");
(function(){T("/dev");gb(259,{read:function(){return 0},write:function(b,c,d,e){return e}});Jb("/dev/null",259);fb(1280,jb);fb(1536,kb);Jb("/dev/tty",1280);Jb("/dev/tty1",1536);var a=bb();U("/dev","random",a);U("/dev","urandom",a);T("/dev/shm");T("/dev/shm/tmp")})();
(function(){T("/proc");var a=T("/proc/self");T("/proc/self/fd");Hb({ua:function(){var b=mb(a,"fd",16895,73);b.la={lookup:function(c,d){var e=P[+d];if(!e)throw new L(8);c={parent:null,ua:{ob:"fake"},la:{readlink:function(){return e.path}}};return c.parent=c}};return b}},"/proc/self/fd")})();var cc;g.FS_createPath=Xb;g.FS_createDataFile=Zb;g.FS_createPreloadedFile=bc;g.FS_createLazyFile=ac;g.FS_createDevice=U;g.FS_unlink=Lb;
function ib(a){var b=Array(wa(a)+1);a=va(a,b,0,b.length);b.length=a;return b}
var Bc={G:function(a,b){Ya||(Ya=!0,Ua());a=new Date(1E3*E[a>>2]);E[b>>2]=a.getSeconds();E[b+4>>2]=a.getMinutes();E[b+8>>2]=a.getHours();E[b+12>>2]=a.getDate();E[b+16>>2]=a.getMonth();E[b+20>>2]=a.getFullYear()-1900;E[b+24>>2]=a.getDay();var c=new Date(a.getFullYear(),0,1);E[b+28>>2]=(a.getTime()-c.getTime())/864E5|0;E[b+36>>2]=-(60*a.getTimezoneOffset());var d=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();c=c.getTimezoneOffset();a=(d!=c&&a.getTimezoneOffset()==Math.min(c,d))|0;E[b+32>>2]=a;
a=E[Xa()+(a?4:0)>>2];E[b+40>>2]=a;return b},K:function(a,b,c,d){try{for(var e=0,f=b?E[b>>2]:0,h=b?E[b+4>>2]:0,n=c?E[c>>2]:0,m=c?E[c+4>>2]:0,t=d?E[d>>2]:0,p=d?E[d+4>>2]:0,r=0,q=0,u=0,x=0,v=0,D=0,F=(b?E[b>>2]:0)|(c?E[c>>2]:0)|(d?E[d>>2]:0),ba=(b?E[b+4>>2]:0)|(c?E[c+4>>2]:0)|(d?E[d+4>>2]:0),K=0;K<a;K++){var B=1<<K%32;if(32>K?F&B:ba&B){var Oa=P[K];if(!Oa)throw new L(8);var Pa=5;Oa.ma.Ra&&(Pa=Oa.ma.Ra(Oa));Pa&1&&(32>K?f&B:h&B)&&(32>K?r|=B:q|=B,e++);Pa&4&&(32>K?n&B:m&B)&&(32>K?u|=B:x|=B,e++);Pa&2&&(32>
K?t&B:p&B)&&(32>K?v|=B:D|=B,e++)}}b&&(E[b>>2]=r,E[b+4>>2]=q);c&&(E[c>>2]=u,E[c+4>>2]=x);d&&(E[d>>2]=v,E[d+4>>2]=D);return e}catch(zb){return"undefined"!==typeof V&&zb instanceof L||y(zb),-zb.oa}},w:function(a,b,c){try{var d=gc(a),e=d.xa.accept(d);b&&kc(b,e.family,oc(e.va),e.za,c);return e.stream.fd}catch(f){return"undefined"!==typeof V&&f instanceof L||y(f),-f.oa}},N:function(a,b){try{a=z(a);if(b&-8)var c=-28;else{var d;(d=R(a,{Ja:!0}).node)?(a="",b&4&&(a+="r"),b&2&&(a+="w"),b&1&&(a+="x"),c=a&&xb(d,
a)?-2:0):c=-44}return c}catch(e){return"undefined"!==typeof V&&e instanceof L||y(e),-e.oa}},z:function(a,b,c){try{var d=gc(a),e=tc(b,c);d.xa.bind(d,e.ra,e.port);return 0}catch(f){return"undefined"!==typeof V&&f instanceof L||y(f),-f.oa}},y:function(a,b,c){try{var d=gc(a),e=tc(b,c);d.xa.connect(d,e.ra,e.port);return 0}catch(f){return"undefined"!==typeof V&&f instanceof L||y(f),-f.oa}},P:function(a){try{var b=W(a);return Pb(b.path,b.flags,0).fd}catch(c){return"undefined"!==typeof V&&c instanceof L||
y(c),-c.oa}},M:function(a,b){try{var c=W(a);if(c.fd===b)var d=b;else{var e=c.path,f=c.flags,h=P[b];h&&Rb(h);d=Pb(e,f,0,b,b).fd}return d}catch(n){return"undefined"!==typeof V&&n instanceof L||y(n),-n.oa}},b:function(a,b,c){ec=c;try{var d=W(a);switch(b){case 0:var e=fc();return 0>e?-28:Pb(d.path,d.flags,0,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=fc(),d.flags|=e,0;case 12:return e=fc(),Ba[e+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return E[yc()>>2]=
28,-1;default:return-28}}catch(f){return"undefined"!==typeof V&&f instanceof L||y(f),-f.oa}},V:function(a,b){try{var c=W(a);return dc(Mb,c.path,b)}catch(d){return"undefined"!==typeof V&&d instanceof L||y(d),-d.oa}},H:function(a,b,c){try{var d=W(a);if(!d.Ga){var e=R(d.path,{Ja:!0}).node;if(!e.la.readdir)throw new L(54);var f=e.la.readdir(e);d.Ga=f}a=0;for(var h=Sb(d,0,1),n=Math.floor(h/280);n<d.Ga.length&&a+280<=c;){var m=d.Ga[n];if("."===m[0]){var t=1;var p=4}else{var r=O(d.node,m);t=r.id;p=8192===
(r.mode&61440)?2:N(r.mode)?4:40960===(r.mode&61440)?10:8}I=[t>>>0,(H=t,1<=+Math.abs(H)?0<H?(Math.min(+Math.floor(H/4294967296),4294967295)|0)>>>0:~~+Math.ceil((H-+(~~H>>>0))/4294967296)>>>0:0)];E[b+a>>2]=I[0];E[b+a+4>>2]=I[1];I=[280*(n+1)>>>0,(H=280*(n+1),1<=+Math.abs(H)?0<H?(Math.min(+Math.floor(H/4294967296),4294967295)|0)>>>0:~~+Math.ceil((H-+(~~H>>>0))/4294967296)>>>0:0)];E[b+a+8>>2]=I[0];E[b+a+12>>2]=I[1];Ba[b+a+16>>1]=280;C[b+a+18>>0]=p;va(m,A,b+a+19,256);a+=280;n+=1}Sb(d,280*n,0);return a}catch(q){return"undefined"!==
typeof V&&q instanceof L||y(q),-q.oa}},O:function(){return 0},v:function(a,b,c){try{var d=gc(a);if(!d.va)return-53;kc(b,d.family,oc(d.va),d.za,c);return 0}catch(e){return"undefined"!==typeof V&&e instanceof L||y(e),-e.oa}},s:function(a,b,c,d,e){try{var f=gc(a);return 1===b&&4===c?(E[d>>2]=f.error,E[e>>2]=4,f.error=null,0):-50}catch(h){return"undefined"!==typeof V&&h instanceof L||y(h),-h.oa}},l:function(a,b,c){ec=c;try{var d=W(a);switch(b){case 21509:case 21505:return d.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.tty?
0:-59;case 21519:if(!d.tty)return-59;var e=fc();return E[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:a=e=fc();if(!d.ma.Pa)throw new L(59);return d.ma.Pa(d,b,a);case 21523:return d.tty?0:-59;case 21524:return d.tty?0:-59;default:y("bad ioctl syscall "+b)}}catch(f){return"undefined"!==typeof V&&f instanceof L||y(f),-f.oa}},x:function(a,b){try{var c=gc(a);c.xa.listen(c,b);return 0}catch(d){return"undefined"!==typeof V&&d instanceof L||y(d),-d.oa}},W:function(a,b){try{return a=z(a),dc(Nb,a,b)}catch(c){return"undefined"!==
typeof V&&c instanceof L||y(c),-c.oa}},X:function(a,b){try{return a=z(a),a=J(a),"/"===a[a.length-1]&&(a=a.substr(0,a.length-1)),T(a,b),0}catch(c){return"undefined"!==typeof V&&c instanceof L||y(c),-c.oa}},m:function(a,b,c){ec=c;try{var d=z(a),e=c?fc():0;return Pb(d,b,e).fd}catch(f){return"undefined"!==typeof V&&f instanceof L||y(f),-f.oa}},Q:function(a){try{if(0==a)throw new L(21);var b=Y.yb();E[a>>2]=b.Fb;E[a+4>>2]=b.Jb;return 0}catch(c){return"undefined"!==typeof V&&c instanceof L||y(c),-c.oa}},
t:function(a,b,c,d,e,f){try{var h=gc(a),n=h.xa.rb(h,c);if(!n)return 0;e&&kc(e,h.family,oc(n.ra),n.port,f);A.set(n.buffer,b);return n.buffer.byteLength}catch(m){return"undefined"!==typeof V&&m instanceof L||y(m),-m.oa}},S:function(a,b){try{a=z(a);b=z(b);var c=$a(a),d=$a(b),e=ab(a),f=ab(b);var h=R(a,{parent:!0});var n=h.node;h=R(b,{parent:!0});var m=h.node;if(!n||!m)throw new L(44);if(n.ua!==m.ua)throw new L(75);var t=O(n,e),p=db(a,d);if("."!==p.charAt(0))throw new L(28);p=db(b,c);if("."!==p.charAt(0))throw new L(55);
try{var r=O(m,f)}catch(x){}if(t!==r){var q=N(t.mode),u=Db(n,e,q);if(u)throw new L(u);if(u=r?Db(m,f,q):Cb(m,f))throw new L(u);if(!n.la.rename)throw new L(63);if(t.Fa||r&&r.Fa)throw new L(10);if(m!==n&&(u=xb(n,"w")))throw new L(u);wb(t);try{n.la.rename(t,m,f)}catch(x){throw x;}finally{vb(t)}}return 0}catch(x){return"undefined"!==typeof V&&x instanceof L||y(x),-x.oa}},T:function(a){try{a=z(a);var b=R(a,{parent:!0}).node,c=ab(a),d=O(b,c),e=Db(b,c,!0);if(e)throw new L(e);if(!b.la.rmdir)throw new L(63);
if(d.Fa)throw new L(10);b.la.rmdir(b,c);wb(d);return 0}catch(f){return"undefined"!==typeof V&&f instanceof L||y(f),-f.oa}},u:function(a,b,c,d,e,f){try{var h=gc(a),n=tc(e,f,!0);return n?h.xa.ub(h,C,b,c,n.ra,n.port):Tb(h.stream,C,b,c)}catch(m){return"undefined"!==typeof V&&m instanceof L||y(m),-m.oa}},r:function(){return-50},h:function(a,b,c){try{return X.createSocket(a,b,c).stream.fd}catch(d){return"undefined"!==typeof V&&d instanceof L||y(d),-d.oa}},n:function(a,b){try{return a=z(a),dc(Mb,a,b)}catch(c){return"undefined"!==
typeof V&&c instanceof L||y(c),-c.oa}},U:function(a){try{return a=z(a),Lb(a),0}catch(b){return"undefined"!==typeof V&&b instanceof L||y(b),-b.oa}},J:function(){return-52},a:function(){y()},R:function(){y("To use dlopen, you need to use Emscripten's linking support, see https://github.com/emscripten-core/emscripten/wiki/Linking")},Y:function(){y("To use dlopen, you need to use Emscripten's linking support, see https://github.com/emscripten-core/emscripten/wiki/Linking")},j:function(){y("To use dlopen, you need to use Emscripten's linking support, see https://github.com/emscripten-core/emscripten/wiki/Linking")},
L:function(){return A.length},A:function(a,b,c){A.copyWithin(a,b,b+c)},B:function(){y("OOM")},E:function(a,b){var c=0;vc().forEach(function(d,e){var f=b+c;E[a+4*e>>2]=f;za(d,f);c+=d.length+1});return 0},F:function(a,b){var c=vc();E[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});E[b>>2]=d;return 0},I:function(){E[yc()>>2]=45;return-1},e:function(a){zc(a)},c:function(a){try{var b=W(a);Rb(b);return 0}catch(c){return"undefined"!==typeof V&&c instanceof L||y(c),c.oa}},C:function(a,b){try{var c=
W(a);C[b>>0]=c.tty?2:N(c.mode)?3:40960===(c.mode&61440)?7:4;return 0}catch(d){return"undefined"!==typeof V&&d instanceof L||y(d),d.oa}},k:function(a,b,c,d){try{a:{for(var e=W(a),f=a=0;f<c;f++){var h=E[b+(8*f+4)>>2],n=e,m=E[b+8*f>>2],t=h,p=void 0,r=C;if(0>t||0>p)throw new L(28);if(null===n.fd)throw new L(8);if(1===(n.flags&2097155))throw new L(8);if(N(n.node.mode))throw new L(31);if(!n.ma.read)throw new L(28);var q="undefined"!==typeof p;if(!q)p=n.position;else if(!n.seekable)throw new L(70);var u=
n.ma.read(n,r,m,t,p);q||(n.position+=u);var x=u;if(0>x){var v=-1;break a}a+=x;if(x<h)break}v=a}E[d>>2]=v;return 0}catch(D){return"undefined"!==typeof V&&D instanceof L||y(D),D.oa}},q:function(a,b,c,d,e){try{var f=W(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;Sb(f,a,d);I=[f.position>>>0,(H=f.position,1<=+Math.abs(H)?0<H?(Math.min(+Math.floor(H/4294967296),4294967295)|0)>>>0:~~+Math.ceil((H-+(~~H>>>0))/4294967296)>>>0:0)];E[e>>2]=I[0];E[e+4>>2]=I[1];f.Ga&&0===a&&
0===d&&(f.Ga=null);return 0}catch(h){return"undefined"!==typeof V&&h instanceof L||y(h),h.oa}},g:function(a,b,c,d){try{a:{for(var e=W(a),f=a=0;f<c;f++){var h=Tb(e,C,E[b+8*f>>2],E[b+(8*f+4)>>2],void 0);if(0>h){var n=-1;break a}a+=h}n=a}E[d>>2]=n;return 0}catch(m){return"undefined"!==typeof V&&m instanceof L||y(m),m.oa}},p:function(){E[yc()>>2]=52;return-1},d:xc,i:function(a,b,c,d){function e(r,q,u,x,v,D){var F=10===r?28:16;v=10===r?qc(v):pc(v);F=ya(F);v=kc(F,r,v,D);assert(!v);v=ya(32);E[v+4>>2]=r;
E[v+8>>2]=q;E[v+12>>2]=u;E[v+24>>2]=x;E[v+20>>2]=F;E[v+16>>2]=10===r?28:16;E[v+28>>2]=0;return v}var f=0,h=0,n=0,m=0,t=0,p=0;c&&(n=E[c>>2],m=E[c+4>>2],t=E[c+8>>2],p=E[c+12>>2]);t&&!p&&(p=2===t?17:6);!t&&p&&(t=17===p?2:1);0===p&&(p=6);0===t&&(t=1);if(!a&&!b)return-2;if(n&-1088||0!==c&&E[c>>2]&2&&!a)return-1;if(n&32)return-2;if(0!==t&&1!==t&&2!==t)return-7;if(0!==m&&2!==m&&10!==m)return-6;if(b&&(b=z(b),h=parseInt(b,10),isNaN(h)))return n&1024?-2:-8;if(!a)return 0===m&&(m=2),0===(n&1)&&(2===m?f=Ac(2130706433):
f=[0,0,0,1]),a=e(m,t,p,null,f,h),E[d>>2]=a,0;a=z(a);f=hc(a);if(null!==f)if(0===m||2===m)m=2;else if(10===m&&n&8)f=[0,0,Ac(65535),f],m=10;else return-2;else if(f=ic(a),null!==f)if(0===m||10===m)m=10;else return-2;if(null!=f)return a=e(m,t,p,a,f,h),E[d>>2]=a,0;if(n&4)return-2;a=oc(a);f=hc(a);0===m?m=2:10===m&&(f=[0,0,Ac(65535),f]);a=e(m,t,p,null,f,h);E[d>>2]=a;return 0},o:function(a){var b=Date.now();E[a>>2]=b/1E3|0;E[a+4>>2]=b%1E3*1E3|0;return 0},D:function(a){zc(a)},f:function(a){0!==a&&A.fill(0,
a,a+16);return 0}};
(function(){function a(e){g.asm=e.exports;ra=g.asm.Z;Aa=e=ra.buffer;g.HEAP8=C=new Int8Array(e);g.HEAP16=Ba=new Int16Array(e);g.HEAP32=E=new Int32Array(e);g.HEAPU8=A=new Uint8Array(e);g.HEAPU16=Ca=new Uint16Array(e);g.HEAPU32=new Uint32Array(e);g.HEAPF32=new Float32Array(e);g.HEAPF64=new Float64Array(e);Da=g.asm.ba;Fa.unshift(g.asm._);Ma("wasm-instantiate")}function b(e){a(e.instance)}function c(e){return Sa().then(function(f){return WebAssembly.instantiate(f,d)}).then(function(f){return f}).then(e,function(f){k("failed to asynchronously prepare wasm: "+
f);y(f)})}var d={a:Bc};La("wasm-instantiate");if(g.instantiateWasm)try{return g.instantiateWasm(d,a)}catch(e){return k("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return qa||"function"!==typeof WebAssembly.instantiateStreaming||Na()||G.startsWith("file://")||"function"!==typeof fetch?c(b):fetch(G,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){k("wasm streaming compile failed: "+f);k("falling back to ArrayBuffer instantiation");
return c(b)})})})();return{}})();g.___wasm_call_ctors=function(){return(g.___wasm_call_ctors=g.asm._).apply(null,arguments)};g._setup=function(){return(g._setup=g.asm.$).apply(null,arguments)};g._process=function(){return(g._process=g.asm.aa).apply(null,arguments)};g._free=function(){return(g._free=g.asm.ca).apply(null,arguments)};
var yc=g.___errno_location=function(){return(yc=g.___errno_location=g.asm.da).apply(null,arguments)},rc=g._ntohs=function(){return(rc=g._ntohs=g.asm.ea).apply(null,arguments)},jc=g._htons=function(){return(jc=g._htons=g.asm.fa).apply(null,arguments)},ya=g._malloc=function(){return(ya=g._malloc=g.asm.ga).apply(null,arguments)},Ac=g._htonl=function(){return(Ac=g._htonl=g.asm.ha).apply(null,arguments)},Xa=g.__get_tzname=function(){return(Xa=g.__get_tzname=g.asm.ia).apply(null,arguments)},Wa=g.__get_daylight=
function(){return(Wa=g.__get_daylight=g.asm.ja).apply(null,arguments)},Va=g.__get_timezone=function(){return(Va=g.__get_timezone=g.asm.ka).apply(null,arguments)};g.addRunDependency=La;g.removeRunDependency=Ma;g.FS_createPath=Xb;g.FS_createDataFile=Zb;g.FS_createPreloadedFile=bc;g.FS_createLazyFile=ac;g.FS_createDevice=U;g.FS_unlink=Lb;var Cc;function na(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Ka=function Dc(){Cc||Ec();Cc||(Ka=Dc)};
function Ec(){function a(){if(!Cc&&(Cc=!0,g.calledRun=!0,!sa)){g.noFSInit||Vb||(Vb=!0,Ub(),g.stdin=g.stdin,g.stdout=g.stdout,g.stderr=g.stderr,g.stdin?U("/dev","stdin",g.stdin):Kb("/dev/tty","/dev/stdin"),g.stdout?U("/dev","stdout",null,g.stdout):Kb("/dev/tty","/dev/stdout"),g.stderr?U("/dev","stderr",null,g.stderr):Kb("/dev/tty1","/dev/stderr"),Pb("/dev/stdin",0),Pb("/dev/stdout",1),Pb("/dev/stderr",1));sb=!1;X.root=Hb(X,null);Y.root=Hb(Y,null);Ta(Fa);if(g.onRuntimeInitialized)g.onRuntimeInitialized();
if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var b=g.postRun.shift();Ga.unshift(b)}Ta(Ga)}}if(!(0<Ia)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Ha();Ta(Ea);0<Ia||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);a()},1)):a())}}g.run=Ec;function zc(a){if(!(noExitRuntime||0<oa)){if(g.onExit)g.onExit(a);sa=!0}da(a,new na(a))}
if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();Ec();
